name: skype-mtd
version: '0.1' 
summary: One Skype for all your devices. New features. New look. All Skype.
description: |

Skype keeps the world talking. Say “hello” with an instant message, voice or video call – all for free, no matter what device they use Skype on. Skype is available on phones, tablets, PCs, Macs and Linux.

Video calls – Don’t just hear the cheers, see it! Get together with 1 or 24 of your friends and family on a video call. Watch your everyone’s smiles and cries when you tell them “We’re engaged!!!"

Chat – Reach people instantly. Send messages to your friends, liven up conversations with emoticons and Mojis, or create a group chat to make weekend plans with up to 300 people.

Share – Do more together. Easily share your screen, photos, videos, documents, and files with your family and friends. Unlike email, Skype will transfer up to 300MB per file.

Voice calls – Camera shy? Make voice calls to anyone on Skype. You can also call mobile and landlines at low rates.

support vietnamese ibus unikey

grade: stable
confinement: strict

parts:
  viber:
    plugin: dump
    source: http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
    source-type: deb
    after: [desktop-glib-only]
    stage-packages:
      - libxss1
      - libssl1.0.0
      - libpulse0
      - libpulse-mainloop-glib0
      - libasound2
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libcurl3
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libsm6
      - libxi6
      - libxtst6
      - libxrandr2
      - libegl1-mesa
      - libxcb-xkb1
      - libxcb-render-util0
      - libxcb-xfixes0
      - libxcb-randr0
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-icccm4
      - libxcb-shape0
      - libxcb-util1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
apps:
  viber:
    command: desktop-launch $SNAP/opt/viber/Viber
    desktop: usr/share/applications/viber.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
     - pulseaudio
     - camera
    environment:
      DISABLE_WAYLAND: 1
      WAYLAND_DISPLAY: no-display
      QTCOMPOSE: $SNAP/usr/share/X11/locale 
